/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package praktikum;

import java.io.File;
import java.io.IOException;

import javafx.application.Application;

import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.fxml.FXMLLoader;

public class App extends Application {
    public static void main(String[] args) {
        Application.launch(args);
    }

    public void start(Stage primaryStage) {
        primaryStage.setTitle("JavaFX FXML Test");

        try {
            File file = new File(
                    "/Users/ramonkostli/projects/GradleProjects/scenebuilder_gradle/app/src/main/resources/scenebuilder.fxml");
            Parent root = FXMLLoader.load(file.toURI().toURL());
            Scene scene = new Scene(root);
            primaryStage.setScene(scene);
            primaryStage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}